### ISSUE TITLE
DayOfYear executions not properly calculated

### ISSUE THREAD

**Issue by jmrozanec** [jmrozanec/cron-utils#184]
DayOfYear executions not properly calculated. See 
- ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.testNextExecutionEveryTwoWeeksStartingWithFirstDayOfYear() 
- ExecutionTimeQuartzWithDayOfYearExtensionIntegrationTest.testLastExecutionEveryTwoWeeksStartingWithFirstDayOfYear()

for details.

**Comment by jmrozanec** [comment]
@meincs could you take a look at this? We merged the PRs, but two tests provided were not passing. We merged to master, and created this issue to look for a solution.

**Comment by meincs** [comment]
@jmrozanec Ok. I try to have a look at the issue tomorrow. Since the test backed by the current day and not fixed I haven't observed the problem yesterday. So I'm goind to add another test fixed to todays date, i.e. 2017-05-20.

**Comment by jmrozanec** [comment]
@meincs That would be great. Thanks! :smile:

**Comment by jmrozanec** [comment]
@meincs thank you for providing a solution with PR #186!

**Comment by jmrozanec** [comment]
@meincs version 6.0.0 was released with this fix!
